version: "3"
services:
  server:
    build:
      dockerfile: Dockerfile
      context: .
    networks:
      - sleep
    ports:
      - "8080:8080"
  module:
    build:
      dockerfile: Dockerfile
      context : ../sleepnode/.
    ports:
      - "3000:3000"
    networks:
      - sleep
networks:
  sleep:
    driver: bridge