version: "3"
services:
  nodejs:
    image: "swellnode:latest"
    ports:
      - "3000:3000"
    depends_on:
      - springboot
  springboot:
    image: "swell:latest"
    ports:
      - "8080:8080"
    restart: always